### ISSUE TITLE
Games in the address bar would help with linking

### ISSUE THREAD

**Issue by sparr** [hcarver/18xx_concordance#1]
`https://18xx.hcarver.com/?1846,1889` or something like that would be very nifty, for linking people directly to a comparison.

**Comment by hcarver** [comment]
Great idea. I'd prefer to have them as named parameters, like `/?game_1=1846&game_2=1889`. Alternatively they could be part of the fragment rather than the query, like `/#game_1=...`. Ideally there would be a simple library we could use which would keep the URL in sync with the state of the React component.
